// ปรับข้อมูล games เป็นแบบนี้ (ลบ id ออก เพิ่ม popupImage ในทุกตัว)
export const games = [
  { popupImage: '/img/popup/aceracer.png', name: 'Ace Racer', image: '/img/listgame/aceracer.png' },
  { popupImage: '/img/popup/blackclover.png', name: 'Black Clover Rise of the Wizard King', image: '/img/listgame/blackclover.png' },
  { popupImage: '/img/popup/brawlstars.png', name: 'Brawl Stars', image: '/img/listgame/brawlstars.png' },
  { popupImage: '/img/popup/eggy.png', name: 'EGGY Party', image: '/img/listgame/eggy.png' },
  { popupImage: '/img/popup/freefire.png', name: 'Free Fire', image: '/img/listgame/freefire.png' },
  { popupImage: '/img/popup/genshin.png', name: 'Genshin Impact', image: '/img/listgame/genshin.png' },
  { popupImage: '/img/popup/goose.png', name: 'Goose Goose Duck', image: '/img/listgame/goose.png' },
  { popupImage: '/img/popup/honkai.png', name: 'Honkai Star Rail', image: '/img/listgame/honkai.png' },
  { popupImage: '/img/popup/honorofkings.png', name: 'Honor Of Kings', image: '/img/listgame/honorofkings.png' },
  { popupImage: '/img/popup/lolwildrift.png', name: 'League Of Legends Wild Rift', image: '/img/listgame/lolwildrift.png' },
  { popupImage: '/img/popup/marvelrivals.png', name: 'Marvel Rivals', image: '/img/listgame/marvelrivals.png' },
  { popupImage: '/img/popup/marvelsnap.png', name: 'Marvel Snap', image: '/img/listgame/marvelsnap.png' },
  { popupImage: '/img/popup/minecraft.png', name: 'Minecraft', image: '/img/listgame/minecraft.png' },
  { popupImage: '/img/popup/myheroes.png', name: 'My Heroes: Dungeon Raid', image: '/img/listgame/myheroes.png' },
  { popupImage: '/img/popup/pokemonunits.png', name: 'Pokemon Units', image: '/img/listgame/pokemonunits.png' },
  { popupImage: '/img/popup/projectbloodstrike.png', name: 'Project Bloodstrike', image: '/img/listgame/projectbloodstrike.png' },
  { popupImage: '/img/popup/pubg.png', name: 'PUBG', image: '/img/listgame/pubg.png' },
  { popupImage: '/img/popup/ragnarok.png', name: 'Ragnarok Origin', image: '/img/listgame/ragnarok.png' },
  { popupImage: '/img/popup/rov.png', name: 'ROV', image: '/img/listgame/rov.png' },
  { popupImage: '/img/popup/slamdunk.png', name: 'Slam Dunk', image: '/img/listgame/slamdunk.png' },
  { popupImage: '/img/popup/squadbusters.png', name: 'Squad Busters', image: '/img/listgame/squadbusters.png' },
  { popupImage: '/img/popup/supersus.png', name: 'SuperSus', image: '/img/listgame/supersus.png' },
  { popupImage: '/img/popup/t3arena.png', name: 'T3 Arena', image: '/img/listgame/t3arena.png' },
  { popupImage: '/img/popup/teamfight.png', name: 'Teamfight Tactics', image: '/img/listgame/teamfight.png' },
  { popupImage: '/img/popup/tower.png', name: 'Tower of Fantasy', image: '/img/listgame/tower.png' },
  { popupImage: '/img/popup/valo.png', name: 'Valorant', image: '/img/listgame/valo.png' },
  { popupImage: '/img/popup/webtoon.png', name: 'Web Toon', image: '/img/listgame/webtoon.png' },
];
